AWSTemplateFormatVersion: 2010-09-09
Description: Simple LAMP Stack

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
  
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the instance will be launched
  
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID where the instance will be launched
  
  DBName:
    Type: String
    Default: myapp
    Description: Database name
  
  DBUser:
    Type: String
    Default: webapp
    Description: Database username
  
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database password
  
  DBRootPassword:
    Type: String
    NoEcho: true
    Description: Database root password
  
  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
    Description: The IP address range that can SSH to the EC2 instance

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP, HTTPS and SSH access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fc5d935ebf8bc3bc  # Ubuntu 22.04 LTS
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get upgrade -y
          
          # Install Apache
          apt-get install -y apache2
          systemctl enable apache2
          systemctl start apache2
          
          # Install PHP
          apt-get install -y php libapache2-mod-php php-mysql php-cli
          
          # Install MySQL
          debconf-set-selections <<< 'mysql-server mysql-server/root_password password ${DBRootPassword}'
          debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password ${DBRootPassword}'
          apt-get install -y mysql-server
          
          # Configure MySQL
          mysql -u root -p${DBRootPassword} -e "CREATE DATABASE ${DBName};"
          mysql -u root -p${DBRootPassword} -e "CREATE USER '${DBUser}'@'localhost' IDENTIFIED BY '${DBPassword}';"
          mysql -u root -p${DBRootPassword} -e "GRANT ALL PRIVILEGES ON ${DBName}.* TO '${DBUser}'@'localhost';"
          mysql -u root -p${DBRootPassword} -e "FLUSH PRIVILEGES;"
          
          # Create a simple PHP test page
          echo "<?php phpinfo(); ?>" > /var/www/html/info.php
          
          # Restart Apache
          systemctl restart apache2
      Tags:
        - Key: Name
          Value: LAMP-WebServer

Outputs:
  WebsiteURL:
    Description: URL for the LAMP stack website
    Value: !Sub "http://${WebServer.PublicIp}"
  
  ApacheTestPage:
    Description: Test PHP info page
    Value: !Sub "http://${WebServer.PublicIp}/info.php"
  
  InstanceId:
    Description: The Instance ID of the LAMP server
    Value: !Ref WebServer